package com.czx.h3dao.po;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

public class H3AccountExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table account
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table account
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table account
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    public H3AccountExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table account
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUidIsNull() {
            addCriterion("uid is null");
            return (Criteria) this;
        }

        public Criteria andUidIsNotNull() {
            addCriterion("uid is not null");
            return (Criteria) this;
        }

        public Criteria andUidEqualTo(String value) {
            addCriterion("uid =", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotEqualTo(String value) {
            addCriterion("uid <>", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThan(String value) {
            addCriterion("uid >", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThanOrEqualTo(String value) {
            addCriterion("uid >=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThan(String value) {
            addCriterion("uid <", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThanOrEqualTo(String value) {
            addCriterion("uid <=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLike(String value) {
            addCriterion("uid like", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotLike(String value) {
            addCriterion("uid not like", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidIn(List<String> values) {
            addCriterion("uid in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotIn(List<String> values) {
            addCriterion("uid not in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidBetween(String value1, String value2) {
            addCriterion("uid between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotBetween(String value1, String value2) {
            addCriterion("uid not between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andPwdIsNull() {
            addCriterion("pwd is null");
            return (Criteria) this;
        }

        public Criteria andPwdIsNotNull() {
            addCriterion("pwd is not null");
            return (Criteria) this;
        }

        public Criteria andPwdEqualTo(String value) {
            addCriterion("pwd =", value, "pwd");
            return (Criteria) this;
        }

        public Criteria andPwdNotEqualTo(String value) {
            addCriterion("pwd <>", value, "pwd");
            return (Criteria) this;
        }

        public Criteria andPwdGreaterThan(String value) {
            addCriterion("pwd >", value, "pwd");
            return (Criteria) this;
        }

        public Criteria andPwdGreaterThanOrEqualTo(String value) {
            addCriterion("pwd >=", value, "pwd");
            return (Criteria) this;
        }

        public Criteria andPwdLessThan(String value) {
            addCriterion("pwd <", value, "pwd");
            return (Criteria) this;
        }

        public Criteria andPwdLessThanOrEqualTo(String value) {
            addCriterion("pwd <=", value, "pwd");
            return (Criteria) this;
        }

        public Criteria andPwdLike(String value) {
            addCriterion("pwd like", value, "pwd");
            return (Criteria) this;
        }

        public Criteria andPwdNotLike(String value) {
            addCriterion("pwd not like", value, "pwd");
            return (Criteria) this;
        }

        public Criteria andPwdIn(List<String> values) {
            addCriterion("pwd in", values, "pwd");
            return (Criteria) this;
        }

        public Criteria andPwdNotIn(List<String> values) {
            addCriterion("pwd not in", values, "pwd");
            return (Criteria) this;
        }

        public Criteria andPwdBetween(String value1, String value2) {
            addCriterion("pwd between", value1, value2, "pwd");
            return (Criteria) this;
        }

        public Criteria andPwdNotBetween(String value1, String value2) {
            addCriterion("pwd not between", value1, value2, "pwd");
            return (Criteria) this;
        }

        public Criteria andSaltIsNull() {
            addCriterion("salt is null");
            return (Criteria) this;
        }

        public Criteria andSaltIsNotNull() {
            addCriterion("salt is not null");
            return (Criteria) this;
        }

        public Criteria andSaltEqualTo(String value) {
            addCriterion("salt =", value, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltNotEqualTo(String value) {
            addCriterion("salt <>", value, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltGreaterThan(String value) {
            addCriterion("salt >", value, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltGreaterThanOrEqualTo(String value) {
            addCriterion("salt >=", value, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltLessThan(String value) {
            addCriterion("salt <", value, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltLessThanOrEqualTo(String value) {
            addCriterion("salt <=", value, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltLike(String value) {
            addCriterion("salt like", value, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltNotLike(String value) {
            addCriterion("salt not like", value, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltIn(List<String> values) {
            addCriterion("salt in", values, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltNotIn(List<String> values) {
            addCriterion("salt not in", values, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltBetween(String value1, String value2) {
            addCriterion("salt between", value1, value2, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltNotBetween(String value1, String value2) {
            addCriterion("salt not between", value1, value2, "salt");
            return (Criteria) this;
        }

        public Criteria andGitAccountIsNull() {
            addCriterion("git_account is null");
            return (Criteria) this;
        }

        public Criteria andGitAccountIsNotNull() {
            addCriterion("git_account is not null");
            return (Criteria) this;
        }

        public Criteria andGitAccountEqualTo(String value) {
            addCriterion("git_account =", value, "gitAccount");
            return (Criteria) this;
        }

        public Criteria andGitAccountNotEqualTo(String value) {
            addCriterion("git_account <>", value, "gitAccount");
            return (Criteria) this;
        }

        public Criteria andGitAccountGreaterThan(String value) {
            addCriterion("git_account >", value, "gitAccount");
            return (Criteria) this;
        }

        public Criteria andGitAccountGreaterThanOrEqualTo(String value) {
            addCriterion("git_account >=", value, "gitAccount");
            return (Criteria) this;
        }

        public Criteria andGitAccountLessThan(String value) {
            addCriterion("git_account <", value, "gitAccount");
            return (Criteria) this;
        }

        public Criteria andGitAccountLessThanOrEqualTo(String value) {
            addCriterion("git_account <=", value, "gitAccount");
            return (Criteria) this;
        }

        public Criteria andGitAccountLike(String value) {
            addCriterion("git_account like", value, "gitAccount");
            return (Criteria) this;
        }

        public Criteria andGitAccountNotLike(String value) {
            addCriterion("git_account not like", value, "gitAccount");
            return (Criteria) this;
        }

        public Criteria andGitAccountIn(List<String> values) {
            addCriterion("git_account in", values, "gitAccount");
            return (Criteria) this;
        }

        public Criteria andGitAccountNotIn(List<String> values) {
            addCriterion("git_account not in", values, "gitAccount");
            return (Criteria) this;
        }

        public Criteria andGitAccountBetween(String value1, String value2) {
            addCriterion("git_account between", value1, value2, "gitAccount");
            return (Criteria) this;
        }

        public Criteria andGitAccountNotBetween(String value1, String value2) {
            addCriterion("git_account not between", value1, value2, "gitAccount");
            return (Criteria) this;
        }

        public Criteria andGitPwdIsNull() {
            addCriterion("git_pwd is null");
            return (Criteria) this;
        }

        public Criteria andGitPwdIsNotNull() {
            addCriterion("git_pwd is not null");
            return (Criteria) this;
        }

        public Criteria andGitPwdEqualTo(String value) {
            addCriterion("git_pwd =", value, "gitPwd");
            return (Criteria) this;
        }

        public Criteria andGitPwdNotEqualTo(String value) {
            addCriterion("git_pwd <>", value, "gitPwd");
            return (Criteria) this;
        }

        public Criteria andGitPwdGreaterThan(String value) {
            addCriterion("git_pwd >", value, "gitPwd");
            return (Criteria) this;
        }

        public Criteria andGitPwdGreaterThanOrEqualTo(String value) {
            addCriterion("git_pwd >=", value, "gitPwd");
            return (Criteria) this;
        }

        public Criteria andGitPwdLessThan(String value) {
            addCriterion("git_pwd <", value, "gitPwd");
            return (Criteria) this;
        }

        public Criteria andGitPwdLessThanOrEqualTo(String value) {
            addCriterion("git_pwd <=", value, "gitPwd");
            return (Criteria) this;
        }

        public Criteria andGitPwdLike(String value) {
            addCriterion("git_pwd like", value, "gitPwd");
            return (Criteria) this;
        }

        public Criteria andGitPwdNotLike(String value) {
            addCriterion("git_pwd not like", value, "gitPwd");
            return (Criteria) this;
        }

        public Criteria andGitPwdIn(List<String> values) {
            addCriterion("git_pwd in", values, "gitPwd");
            return (Criteria) this;
        }

        public Criteria andGitPwdNotIn(List<String> values) {
            addCriterion("git_pwd not in", values, "gitPwd");
            return (Criteria) this;
        }

        public Criteria andGitPwdBetween(String value1, String value2) {
            addCriterion("git_pwd between", value1, value2, "gitPwd");
            return (Criteria) this;
        }

        public Criteria andGitPwdNotBetween(String value1, String value2) {
            addCriterion("git_pwd not between", value1, value2, "gitPwd");
            return (Criteria) this;
        }

        public Criteria andGitOpenedIsNull() {
            addCriterion("git_opened is null");
            return (Criteria) this;
        }

        public Criteria andGitOpenedIsNotNull() {
            addCriterion("git_opened is not null");
            return (Criteria) this;
        }

        public Criteria andGitOpenedEqualTo(Short value) {
            addCriterion("git_opened =", value, "gitOpened");
            return (Criteria) this;
        }

        public Criteria andGitOpenedNotEqualTo(Short value) {
            addCriterion("git_opened <>", value, "gitOpened");
            return (Criteria) this;
        }

        public Criteria andGitOpenedGreaterThan(Short value) {
            addCriterion("git_opened >", value, "gitOpened");
            return (Criteria) this;
        }

        public Criteria andGitOpenedGreaterThanOrEqualTo(Short value) {
            addCriterion("git_opened >=", value, "gitOpened");
            return (Criteria) this;
        }

        public Criteria andGitOpenedLessThan(Short value) {
            addCriterion("git_opened <", value, "gitOpened");
            return (Criteria) this;
        }

        public Criteria andGitOpenedLessThanOrEqualTo(Short value) {
            addCriterion("git_opened <=", value, "gitOpened");
            return (Criteria) this;
        }

        public Criteria andGitOpenedIn(List<Short> values) {
            addCriterion("git_opened in", values, "gitOpened");
            return (Criteria) this;
        }

        public Criteria andGitOpenedNotIn(List<Short> values) {
            addCriterion("git_opened not in", values, "gitOpened");
            return (Criteria) this;
        }

        public Criteria andGitOpenedBetween(Short value1, Short value2) {
            addCriterion("git_opened between", value1, value2, "gitOpened");
            return (Criteria) this;
        }

        public Criteria andGitOpenedNotBetween(Short value1, Short value2) {
            addCriterion("git_opened not between", value1, value2, "gitOpened");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Short value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Short value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Short value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Short value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Short value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Short value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Short> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Short> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Short value1, Short value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Short value1, Short value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(LocalDateTime value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(LocalDateTime value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(LocalDateTime value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(LocalDateTime value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<LocalDateTime> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<LocalDateTime> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNull() {
            addCriterion("modify_time is null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNotNull() {
            addCriterion("modify_time is not null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeEqualTo(LocalDateTime value) {
            addCriterion("modify_time =", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotEqualTo(LocalDateTime value) {
            addCriterion("modify_time <>", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThan(LocalDateTime value) {
            addCriterion("modify_time >", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("modify_time >=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThan(LocalDateTime value) {
            addCriterion("modify_time <", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("modify_time <=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIn(List<LocalDateTime> values) {
            addCriterion("modify_time in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotIn(List<LocalDateTime> values) {
            addCriterion("modify_time not in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("modify_time between", value1, value2, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("modify_time not between", value1, value2, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andSysVerIsNull() {
            addCriterion("sys_ver is null");
            return (Criteria) this;
        }

        public Criteria andSysVerIsNotNull() {
            addCriterion("sys_ver is not null");
            return (Criteria) this;
        }

        public Criteria andSysVerEqualTo(Integer value) {
            addCriterion("sys_ver =", value, "sysVer");
            return (Criteria) this;
        }

        public Criteria andSysVerNotEqualTo(Integer value) {
            addCriterion("sys_ver <>", value, "sysVer");
            return (Criteria) this;
        }

        public Criteria andSysVerGreaterThan(Integer value) {
            addCriterion("sys_ver >", value, "sysVer");
            return (Criteria) this;
        }

        public Criteria andSysVerGreaterThanOrEqualTo(Integer value) {
            addCriterion("sys_ver >=", value, "sysVer");
            return (Criteria) this;
        }

        public Criteria andSysVerLessThan(Integer value) {
            addCriterion("sys_ver <", value, "sysVer");
            return (Criteria) this;
        }

        public Criteria andSysVerLessThanOrEqualTo(Integer value) {
            addCriterion("sys_ver <=", value, "sysVer");
            return (Criteria) this;
        }

        public Criteria andSysVerIn(List<Integer> values) {
            addCriterion("sys_ver in", values, "sysVer");
            return (Criteria) this;
        }

        public Criteria andSysVerNotIn(List<Integer> values) {
            addCriterion("sys_ver not in", values, "sysVer");
            return (Criteria) this;
        }

        public Criteria andSysVerBetween(Integer value1, Integer value2) {
            addCriterion("sys_ver between", value1, value2, "sysVer");
            return (Criteria) this;
        }

        public Criteria andSysVerNotBetween(Integer value1, Integer value2) {
            addCriterion("sys_ver not between", value1, value2, "sysVer");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table account
     *
     * @mbg.generated do_not_delete_during_merge Sat Oct 02 10:12:59 CST 2021
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table account
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}