package com.czx.h3dao.po;

import java.time.LocalDateTime;

public class H3Account {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.id
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.uid
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    private String uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.pwd
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    private String pwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.salt
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    private String salt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.git_account
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    private String gitAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.git_pwd
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    private String gitPwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.git_opened
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    private Short gitOpened;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.status
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    private Short status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.create_time
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    private LocalDateTime createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.modify_time
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    private LocalDateTime modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.sys_ver
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    private Integer sysVer;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.id
     *
     * @return the value of account.id
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.id
     *
     * @param id the value for account.id
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.uid
     *
     * @return the value of account.uid
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.uid
     *
     * @param uid the value for account.uid
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.pwd
     *
     * @return the value of account.pwd
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.pwd
     *
     * @param pwd the value for account.pwd
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    public void setPwd(String pwd) {
        this.pwd = pwd == null ? null : pwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.salt
     *
     * @return the value of account.salt
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.salt
     *
     * @param salt the value for account.salt
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    public void setSalt(String salt) {
        this.salt = salt == null ? null : salt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.git_account
     *
     * @return the value of account.git_account
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    public String getGitAccount() {
        return gitAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.git_account
     *
     * @param gitAccount the value for account.git_account
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    public void setGitAccount(String gitAccount) {
        this.gitAccount = gitAccount == null ? null : gitAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.git_pwd
     *
     * @return the value of account.git_pwd
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    public String getGitPwd() {
        return gitPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.git_pwd
     *
     * @param gitPwd the value for account.git_pwd
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    public void setGitPwd(String gitPwd) {
        this.gitPwd = gitPwd == null ? null : gitPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.git_opened
     *
     * @return the value of account.git_opened
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    public Short getGitOpened() {
        return gitOpened;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.git_opened
     *
     * @param gitOpened the value for account.git_opened
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    public void setGitOpened(Short gitOpened) {
        this.gitOpened = gitOpened;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.status
     *
     * @return the value of account.status
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.status
     *
     * @param status the value for account.status
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.create_time
     *
     * @return the value of account.create_time
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    public LocalDateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.create_time
     *
     * @param createTime the value for account.create_time
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.modify_time
     *
     * @return the value of account.modify_time
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    public LocalDateTime getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.modify_time
     *
     * @param modifyTime the value for account.modify_time
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    public void setModifyTime(LocalDateTime modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.sys_ver
     *
     * @return the value of account.sys_ver
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    public Integer getSysVer() {
        return sysVer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.sys_ver
     *
     * @param sysVer the value for account.sys_ver
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    public void setSysVer(Integer sysVer) {
        this.sysVer = sysVer;
    }
}