package com.czx.h3dao.po;

import java.time.LocalDateTime;

public class H3HomeSpace {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column homespace.id
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column homespace.home_name
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    private String homeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column homespace.home_salt
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    private String homeSalt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column homespace.uid
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    private String uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column homespace.create_time
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    private LocalDateTime createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column homespace.modify_time
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    private LocalDateTime modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column homespace.id
     *
     * @return the value of homespace.id
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column homespace.id
     *
     * @param id the value for homespace.id
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column homespace.home_name
     *
     * @return the value of homespace.home_name
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    public String getHomeName() {
        return homeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column homespace.home_name
     *
     * @param homeName the value for homespace.home_name
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    public void setHomeName(String homeName) {
        this.homeName = homeName == null ? null : homeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column homespace.home_salt
     *
     * @return the value of homespace.home_salt
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    public String getHomeSalt() {
        return homeSalt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column homespace.home_salt
     *
     * @param homeSalt the value for homespace.home_salt
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    public void setHomeSalt(String homeSalt) {
        this.homeSalt = homeSalt == null ? null : homeSalt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column homespace.uid
     *
     * @return the value of homespace.uid
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column homespace.uid
     *
     * @param uid the value for homespace.uid
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column homespace.create_time
     *
     * @return the value of homespace.create_time
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    public LocalDateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column homespace.create_time
     *
     * @param createTime the value for homespace.create_time
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column homespace.modify_time
     *
     * @return the value of homespace.modify_time
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    public LocalDateTime getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column homespace.modify_time
     *
     * @param modifyTime the value for homespace.modify_time
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    public void setModifyTime(LocalDateTime modifyTime) {
        this.modifyTime = modifyTime;
    }
}