package com.czx.h3dao.po;

import java.time.LocalDateTime;

public class H3KeyVault {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column keyvault.key_name
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    private String keyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column keyvault.key_salt
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    private String keySalt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column keyvault.create_time
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    private LocalDateTime createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column keyvault.modify_time
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    private LocalDateTime modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column keyvault.key_name
     *
     * @return the value of keyvault.key_name
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    public String getKeyName() {
        return keyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column keyvault.key_name
     *
     * @param keyName the value for keyvault.key_name
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    public void setKeyName(String keyName) {
        this.keyName = keyName == null ? null : keyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column keyvault.key_salt
     *
     * @return the value of keyvault.key_salt
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    public String getKeySalt() {
        return keySalt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column keyvault.key_salt
     *
     * @param keySalt the value for keyvault.key_salt
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    public void setKeySalt(String keySalt) {
        this.keySalt = keySalt == null ? null : keySalt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column keyvault.create_time
     *
     * @return the value of keyvault.create_time
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    public LocalDateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column keyvault.create_time
     *
     * @param createTime the value for keyvault.create_time
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column keyvault.modify_time
     *
     * @return the value of keyvault.modify_time
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    public LocalDateTime getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column keyvault.modify_time
     *
     * @param modifyTime the value for keyvault.modify_time
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    public void setModifyTime(LocalDateTime modifyTime) {
        this.modifyTime = modifyTime;
    }
}