package com.czx.h3dao.po;

import java.time.LocalDateTime;

public class H3OpenIds {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column openids.id
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column openids.open_id
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    private String openId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column openids.id_type
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    private Short idType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column openids.uid
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    private String uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column openids.status
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    private Short status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column openids.create_time
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    private LocalDateTime createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column openids.modify_time
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    private LocalDateTime modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column openids.sys_ver
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    private Integer sysVer;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column openids.id
     *
     * @return the value of openids.id
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column openids.id
     *
     * @param id the value for openids.id
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column openids.open_id
     *
     * @return the value of openids.open_id
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column openids.open_id
     *
     * @param openId the value for openids.open_id
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    public void setOpenId(String openId) {
        this.openId = openId == null ? null : openId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column openids.id_type
     *
     * @return the value of openids.id_type
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    public Short getIdType() {
        return idType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column openids.id_type
     *
     * @param idType the value for openids.id_type
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    public void setIdType(Short idType) {
        this.idType = idType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column openids.uid
     *
     * @return the value of openids.uid
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column openids.uid
     *
     * @param uid the value for openids.uid
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column openids.status
     *
     * @return the value of openids.status
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column openids.status
     *
     * @param status the value for openids.status
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column openids.create_time
     *
     * @return the value of openids.create_time
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    public LocalDateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column openids.create_time
     *
     * @param createTime the value for openids.create_time
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column openids.modify_time
     *
     * @return the value of openids.modify_time
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    public LocalDateTime getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column openids.modify_time
     *
     * @param modifyTime the value for openids.modify_time
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    public void setModifyTime(LocalDateTime modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column openids.sys_ver
     *
     * @return the value of openids.sys_ver
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    public Integer getSysVer() {
        return sysVer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column openids.sys_ver
     *
     * @param sysVer the value for openids.sys_ver
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    public void setSysVer(Integer sysVer) {
        this.sysVer = sysVer;
    }
}