package com.czx.h3dao.mapper;

import com.czx.h3dao.po.H3Account;
import com.czx.h3dao.po.H3AccountExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface H3AccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    long countByExample(H3AccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    int deleteByExample(H3AccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    int insert(H3Account record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    int insertSelective(H3Account record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    List<H3Account> selectByExample(H3AccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    H3Account selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    int updateByExampleSelective(@Param("record") H3Account record, @Param("example") H3AccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    int updateByExample(@Param("record") H3Account record, @Param("example") H3AccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    int updateByPrimaryKeySelective(H3Account record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    int updateByPrimaryKey(H3Account record);
}