package com.czx.h3dao.mapper;

import com.czx.h3dao.po.H3HomeSpace;
import com.czx.h3dao.po.H3HomeSpaceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface H3HomeSpaceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homespace
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    long countByExample(H3HomeSpaceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homespace
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    int deleteByExample(H3HomeSpaceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homespace
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homespace
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    int insert(H3HomeSpace record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homespace
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    int insertSelective(H3HomeSpace record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homespace
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    List<H3HomeSpace> selectByExample(H3HomeSpaceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homespace
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    H3HomeSpace selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homespace
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    int updateByExampleSelective(@Param("record") H3HomeSpace record, @Param("example") H3HomeSpaceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homespace
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    int updateByExample(@Param("record") H3HomeSpace record, @Param("example") H3HomeSpaceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homespace
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    int updateByPrimaryKeySelective(H3HomeSpace record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homespace
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    int updateByPrimaryKey(H3HomeSpace record);
}