package com.czx.h3dao.mapper;

import com.czx.h3dao.po.H3KeyVault;
import com.czx.h3dao.po.H3KeyVaultExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface H3KeyVaultMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table keyvault
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    long countByExample(H3KeyVaultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table keyvault
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    int deleteByExample(H3KeyVaultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table keyvault
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    int deleteByPrimaryKey(String keyName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table keyvault
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    int insert(H3KeyVault record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table keyvault
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    int insertSelective(H3KeyVault record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table keyvault
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    List<H3KeyVault> selectByExample(H3KeyVaultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table keyvault
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    H3KeyVault selectByPrimaryKey(String keyName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table keyvault
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    int updateByExampleSelective(@Param("record") H3KeyVault record, @Param("example") H3KeyVaultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table keyvault
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    int updateByExample(@Param("record") H3KeyVault record, @Param("example") H3KeyVaultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table keyvault
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    int updateByPrimaryKeySelective(H3KeyVault record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table keyvault
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    int updateByPrimaryKey(H3KeyVault record);
}