package com.czx.h3dao.mapper;

import com.czx.h3dao.po.H3OpenIds;
import com.czx.h3dao.po.H3OpenIdsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface H3OpenIdsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table openids
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    long countByExample(H3OpenIdsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table openids
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    int deleteByExample(H3OpenIdsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table openids
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table openids
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    int insert(H3OpenIds record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table openids
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    int insertSelective(H3OpenIds record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table openids
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    List<H3OpenIds> selectByExample(H3OpenIdsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table openids
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    H3OpenIds selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table openids
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    int updateByExampleSelective(@Param("record") H3OpenIds record, @Param("example") H3OpenIdsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table openids
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    int updateByExample(@Param("record") H3OpenIds record, @Param("example") H3OpenIdsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table openids
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    int updateByPrimaryKeySelective(H3OpenIds record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table openids
     *
     * @mbg.generated Sat Oct 02 10:12:59 CST 2021
     */
    int updateByPrimaryKey(H3OpenIds record);
}